export const mockBuses = [
  {
    id: '1',
    bus_number: 'KA-01-AB-1234',
    route_name: 'Bangalore - Mysore',
    capacity: 45,
    status: 'offline' as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    bus_number: 'KA-02-CD-5678',
    route_name: 'Bangalore - Hubli',
    capacity: 50,
    status: 'online' as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    latest_location: {
      id: '1',
      bus_id: '2',
      trip_id: '1',
      latitude: 12.9716,
      longitude: 77.5946,
      speed: 45,
      accuracy: 10,
      timestamp: new Date().toISOString(),
      created_at: new Date().toISOString(),
    },
    current_trip: {
      id: '1',
      bus_id: '2',
      conductor_name: 'Rajesh Kumar',
      start_time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      end_time: null,
      status: 'active' as const,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: '3',
    bus_number: 'KA-03-EF-9012',
    route_name: 'Mysore - Hassan',
    capacity: 40,
    status: 'online' as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    latest_location: {
      id: '2',
      bus_id: '3',
      trip_id: '2',
      latitude: 12.3056,
      longitude: 76.6553,
      speed: 32,
      accuracy: 8,
      timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      created_at: new Date().toISOString(),
    },
    current_trip: {
      id: '2',
      bus_id: '3',
      conductor_name: 'Suresh Reddy',
      start_time: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      end_time: null,
      status: 'active' as const,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: '4',
    bus_number: 'KA-04-GH-3456',
    route_name: 'Hubli - Belgaum',
    capacity: 48,
    status: 'offline' as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    bus_number: 'KA-05-IJ-7890',
    route_name: 'Bangalore - Mangalore',
    capacity: 52,
    status: 'offline' as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];